%% Lift vs AoA — Report / Poster Style
clear; clc; close all;

%% Data
AoA = (1:16)';

% Model 1 — Baseline
lift1 = [136.02,136.94,138.02,139.06,140.04,141.02,142.01,...
         143.04,144.19,145.54,147.21,148.80,148.63,148.04,...
         147.18,148.44]';

% Model 5 — Final
lift5 = [152.03,152.71,153.87,155.01,156.13,157.23,158.35,...
         159.54,160.87,162.48,164.47,166.51,166.55,165.23,...
         165.41,164.55]';

%% Key values
[maxLift1, iStall1] = max(lift1);
stallAoA1 = AoA(iStall1);

[maxLift5, iStall5] = max(lift5);
stallAoA5 = AoA(iStall5);

avgDiff = mean((lift5 - lift1)./lift1 * 100);

%% Style
fnt = 'Calibri';

c1 = [0 0 0];         % black
c5 = [0.35 0.35 0.35]; % dark grey

lw = 4;
ms = 13;

tickFont  = 26;
labelFont = 32;
titleFont = 38;
legendFont = 20;
noteFont  = 24;

%% Figure — taller aspect ratio
fig = figure('Color','w',...
    'Units','centimeters',...
    'Position',[2 2 18 24]);

hold on;
grid on;
box on;

ax = gca;
ax.FontName = fnt;
ax.FontSize = tickFont;
ax.FontWeight = 'bold';
ax.LineWidth = 2;
ax.GridAlpha = 0.18;
ax.MinorGridAlpha = 0.08;

%% Curves
plot(AoA, lift1, '-o', ...
    'Color', c1, ...
    'LineWidth', lw, ...
    'MarkerSize', ms, ...
    'MarkerFaceColor', 'w', ...
    'DisplayName', sprintf('Model 1  |  Max = %.1f N', maxLift1));

plot(AoA, lift5, '-s', ...
    'Color', c5, ...
    'LineWidth', lw, ...
    'MarkerSize', ms, ...
    'MarkerFaceColor', 'w', ...
    'DisplayName', sprintf('Model 5  |  Max = %.1f N  |  +%.1f%% avg.', ...
    maxLift5, avgDiff));

%% Stall markers
plot(stallAoA1, maxLift1, 'v', ...
    'Color', c1, ...
    'MarkerSize', 18, ...
    'MarkerFaceColor', c1, ...
    'HandleVisibility','off');

plot(stallAoA5, maxLift5, 'v', ...
    'Color', c5, ...
    'MarkerSize', 18, ...
    'MarkerFaceColor', c5, ...
    'HandleVisibility','off');

%% Annotations
text(stallAoA1 + 0.2, maxLift1 - 1.4, ...
    sprintf('Stall @ %d°', stallAoA1), ...
    'FontName', fnt, ...
    'FontSize', noteFont, ...
    'FontWeight','bold', ...
    'Color', c1);

text(stallAoA5 + 0.2, maxLift5 - 1.4, ...
    sprintf('Stall @ %d°', stallAoA5), ...
    'FontName', fnt, ...
    'FontSize', noteFont, ...
    'FontWeight','bold', ...
    'Color', c5);

%% Labels
xlabel('Angle of Attack, \alpha (deg)', ...
    'FontName', fnt, ...
    'FontSize', labelFont, ...
    'FontWeight','bold');

ylabel('Lift (N)', ...
    'FontName', fnt, ...
    'FontSize', labelFont, ...
    'FontWeight','bold');

title('Lift vs Angle of Attack', ...
    'FontName', fnt, ...
    'FontSize', titleFont, ...
    'FontWeight','bold');

%% Legend
lg = legend('Location','northwest');

set(lg, ...
    'FontName', fnt, ...
    'FontSize', legendFont, ...
    'Box','on');

%% Limits
xlim([1 16]);
ylim([132 170]);

xticks(1:16);

%% Export
exportgraphics(fig, ...
    'Lift_vs_AoA_report_style.png', ...
    'Resolution', 600);

exportgraphics(fig, ...
    'Lift_vs_AoA_report_style.pdf', ...
    'ContentType', 'vector');